/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoItGUIConcept;

/**
 *
 * @author soneg
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        navJPanel = new javax.swing.JPanel();
        doItLabel = new javax.swing.JLabel();
        importanteJPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usuarioJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        quadro1JPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        quadro2JPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        quadro3JPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        concluidasJPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        atrasadoJPanel = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        listJPanel = new javax.swing.JPanel();
        overviewJPanel = new javax.swing.JPanel();
        tarefaLabel = new javax.swing.JLabel();
        textoTarefaLabel = new javax.swing.JLabel();
        dataIconLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        nomeListaLabel = new javax.swing.JLabel();
        listaJPanel = new javax.swing.JPanel();
        tarefa1JPanel = new javax.swing.JPanel();
        trashIconLabel1 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        tarefa2JPanel = new javax.swing.JPanel();
        jLabel203 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        tarefa3JPanel = new javax.swing.JPanel();
        trashIconLabel3 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        tarefa4JPanel = new javax.swing.JPanel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        trashIconLabel4 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setText("jLabel26");

        setBackground(new java.awt.Color(34, 47, 62));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.setMinimumSize(new java.awt.Dimension(980, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navJPanel.setBackground(new java.awt.Color(44, 62, 80));
        navJPanel.setMinimumSize(new java.awt.Dimension(300, 720));

        doItLabel.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        doItLabel.setForeground(new java.awt.Color(255, 255, 255));
        doItLabel.setText("Do It!");

        importanteJPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_important_property_32px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Importante");

        javax.swing.GroupLayout importanteJPanelLayout = new javax.swing.GroupLayout(importanteJPanel);
        importanteJPanel.setLayout(importanteJPanelLayout);
        importanteJPanelLayout.setHorizontalGroup(
            importanteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importanteJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        importanteJPanelLayout.setVerticalGroup(
            importanteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importanteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importanteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        usuarioJPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_gender_neutral_user_32px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuário");

        javax.swing.GroupLayout usuarioJPanelLayout = new javax.swing.GroupLayout(usuarioJPanel);
        usuarioJPanel.setLayout(usuarioJPanelLayout);
        usuarioJPanelLayout.setHorizontalGroup(
            usuarioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(40, 40, 40)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        usuarioJPanelLayout.setVerticalGroup(
            usuarioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuarioJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuarioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        quadro1JPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_tasklist_32px.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Quadro 1");

        javax.swing.GroupLayout quadro1JPanelLayout = new javax.swing.GroupLayout(quadro1JPanel);
        quadro1JPanel.setLayout(quadro1JPanelLayout);
        quadro1JPanelLayout.setHorizontalGroup(
            quadro1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadro1JPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(41, 41, 41)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        quadro1JPanelLayout.setVerticalGroup(
            quadro1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadro1JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadro1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        quadro2JPanel.setBackground(new java.awt.Color(41, 128, 185));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_tasklist_32px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Quadro 2");

        javax.swing.GroupLayout quadro2JPanelLayout = new javax.swing.GroupLayout(quadro2JPanel);
        quadro2JPanel.setLayout(quadro2JPanelLayout);
        quadro2JPanelLayout.setHorizontalGroup(
            quadro2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadro2JPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(41, 41, 41)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        quadro2JPanelLayout.setVerticalGroup(
            quadro2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadro2JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadro2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        quadro3JPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_tasklist_32px.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Quadro 3");

        javax.swing.GroupLayout quadro3JPanelLayout = new javax.swing.GroupLayout(quadro3JPanel);
        quadro3JPanel.setLayout(quadro3JPanelLayout);
        quadro3JPanelLayout.setHorizontalGroup(
            quadro3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadro3JPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addGap(41, 41, 41)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        quadro3JPanelLayout.setVerticalGroup(
            quadro3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadro3JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadro3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        concluidasJPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_checkmark_26px.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Concluídas");

        javax.swing.GroupLayout concluidasJPanelLayout = new javax.swing.GroupLayout(concluidasJPanel);
        concluidasJPanel.setLayout(concluidasJPanelLayout);
        concluidasJPanelLayout.setHorizontalGroup(
            concluidasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concluidasJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21)
                .addGap(41, 41, 41)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        concluidasJPanelLayout.setVerticalGroup(
            concluidasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concluidasJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(concluidasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        atrasadoJPanel.setBackground(new java.awt.Color(52, 73, 94));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_expired_32px.png"))); // NOI18N

        jLabel211.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel211.setForeground(new java.awt.Color(255, 255, 255));
        jLabel211.setText("Atrasado");

        javax.swing.GroupLayout atrasadoJPanelLayout = new javax.swing.GroupLayout(atrasadoJPanel);
        atrasadoJPanel.setLayout(atrasadoJPanelLayout);
        atrasadoJPanelLayout.setHorizontalGroup(
            atrasadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atrasadoJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel46)
                .addGap(41, 41, 41)
                .addComponent(jLabel211, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        atrasadoJPanelLayout.setVerticalGroup(
            atrasadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atrasadoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atrasadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel211, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout navJPanelLayout = new javax.swing.GroupLayout(navJPanel);
        navJPanel.setLayout(navJPanelLayout);
        navJPanelLayout.setHorizontalGroup(
            navJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(importanteJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(navJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(doItLabel)
                .addContainerGap(119, Short.MAX_VALUE))
            .addComponent(usuarioJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(quadro1JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(quadro2JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(quadro3JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(concluidasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atrasadoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navJPanelLayout.setVerticalGroup(
            navJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doItLabel)
                .addGap(18, 18, 18)
                .addComponent(usuarioJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(importanteJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atrasadoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(quadro1JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quadro2JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quadro3JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(concluidasJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        listJPanel.setBackground(new java.awt.Color(34, 47, 62));

        overviewJPanel.setBackground(new java.awt.Color(41, 128, 185));

        tarefaLabel.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        tarefaLabel.setForeground(new java.awt.Color(255, 255, 255));
        tarefaLabel.setText("Tarefa 3");

        textoTarefaLabel.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        textoTarefaLabel.setForeground(new java.awt.Color(255, 255, 255));
        textoTarefaLabel.setText("<html><body>Mussum Ipsum, cacilds vidis litro abertis. Quem manda na minha terra sou euzis! Diuretics paradis num copo é motivis de denguis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Quem num gosta di mé, boa gentis num é.  </body></html>");

        dataIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_property_time_32px.png"))); // NOI18N

        dataLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataLabel.setText("10/12/19");

        javax.swing.GroupLayout overviewJPanelLayout = new javax.swing.GroupLayout(overviewJPanel);
        overviewJPanel.setLayout(overviewJPanelLayout);
        overviewJPanelLayout.setHorizontalGroup(
            overviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overviewJPanelLayout.createSequentialGroup()
                        .addComponent(tarefaLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoTarefaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewJPanelLayout.createSequentialGroup()
                        .addGap(0, 739, Short.MAX_VALUE)
                        .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataIconLabel)))
                .addContainerGap())
        );
        overviewJPanelLayout.setVerticalGroup(
            overviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tarefaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTarefaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewJPanelLayout.createSequentialGroup()
                        .addComponent(dataIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewJPanelLayout.createSequentialGroup()
                        .addComponent(dataLabel)
                        .addGap(22, 22, 22))))
        );

        nomeListaLabel.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        nomeListaLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeListaLabel.setText("Quadro 2");

        listaJPanel.setBackground(new java.awt.Color(52, 73, 94));

        tarefa1JPanel.setBackground(new java.awt.Color(44, 62, 80));

        trashIconLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_trash_32px_2.png"))); // NOI18N

        jLabel180.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_checkmark_26px.png"))); // NOI18N

        jLabel181.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_important_property_32px.png"))); // NOI18N

        jLabel202.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel202.setForeground(new java.awt.Color(255, 255, 255));
        jLabel202.setText("Tarefa 1");

        javax.swing.GroupLayout tarefa1JPanelLayout = new javax.swing.GroupLayout(tarefa1JPanel);
        tarefa1JPanel.setLayout(tarefa1JPanelLayout);
        tarefa1JPanelLayout.setHorizontalGroup(
            tarefa1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa1JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel202, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel181)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel180)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trashIconLabel1)
                .addContainerGap())
        );
        tarefa1JPanelLayout.setVerticalGroup(
            tarefa1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa1JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tarefa1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trashIconLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel180, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel181, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel202, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tarefa2JPanel.setBackground(new java.awt.Color(44, 62, 80));

        jLabel203.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel203.setForeground(new java.awt.Color(255, 255, 255));
        jLabel203.setText("Tarefa 2");

        jLabel198.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_important_property_32px.png"))); // NOI18N

        jLabel199.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_checkmark_26px.png"))); // NOI18N

        jLabel200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_trash_32px_2.png"))); // NOI18N

        javax.swing.GroupLayout tarefa2JPanelLayout = new javax.swing.GroupLayout(tarefa2JPanel);
        tarefa2JPanel.setLayout(tarefa2JPanelLayout);
        tarefa2JPanelLayout.setHorizontalGroup(
            tarefa2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa2JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel203, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel198)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel199)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel200)
                .addContainerGap())
        );
        tarefa2JPanelLayout.setVerticalGroup(
            tarefa2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa2JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tarefa2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel199, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel198, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel203, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tarefa3JPanel.setBackground(new java.awt.Color(41, 128, 185));

        trashIconLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_trash_32px_2.png"))); // NOI18N

        jLabel205.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_checkmark_26px.png"))); // NOI18N

        jLabel204.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel204.setForeground(new java.awt.Color(255, 255, 255));
        jLabel204.setText("Tarefa 3");

        jLabel201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_important_property_32px.png"))); // NOI18N

        javax.swing.GroupLayout tarefa3JPanelLayout = new javax.swing.GroupLayout(tarefa3JPanel);
        tarefa3JPanel.setLayout(tarefa3JPanelLayout);
        tarefa3JPanelLayout.setHorizontalGroup(
            tarefa3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa3JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel204, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel201)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel205)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trashIconLabel3)
                .addContainerGap())
        );
        tarefa3JPanelLayout.setVerticalGroup(
            tarefa3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tarefa3JPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tarefa3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trashIconLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel205, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel204, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tarefa4JPanel.setBackground(new java.awt.Color(44, 62, 80));

        jLabel207.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel207.setForeground(new java.awt.Color(255, 255, 255));
        jLabel207.setText("Tarefa 4");

        jLabel208.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_important_property_32px.png"))); // NOI18N

        trashIconLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_trash_32px_2.png"))); // NOI18N

        jLabel209.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoItGUIConcept/images/icons8_checkmark_26px.png"))); // NOI18N

        javax.swing.GroupLayout tarefa4JPanelLayout = new javax.swing.GroupLayout(tarefa4JPanel);
        tarefa4JPanel.setLayout(tarefa4JPanelLayout);
        tarefa4JPanelLayout.setHorizontalGroup(
            tarefa4JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa4JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel207, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel208)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel209)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trashIconLabel4)
                .addContainerGap())
        );
        tarefa4JPanelLayout.setVerticalGroup(
            tarefa4JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarefa4JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tarefa4JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trashIconLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel209, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel208, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel207, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout listaJPanelLayout = new javax.swing.GroupLayout(listaJPanel);
        listaJPanel.setLayout(listaJPanelLayout);
        listaJPanelLayout.setHorizontalGroup(
            listaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tarefa1JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarefa2JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarefa3JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarefa4JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        listaJPanelLayout.setVerticalGroup(
            listaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tarefa1JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarefa2JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarefa3JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarefa4JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listJPanelLayout = new javax.swing.GroupLayout(listJPanel);
        listJPanel.setLayout(listJPanelLayout);
        listJPanelLayout.setHorizontalGroup(
            listJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeListaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        listJPanelLayout.setVerticalGroup(
            listJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overviewJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeListaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(navJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atrasadoJPanel;
    private javax.swing.JPanel concluidasJPanel;
    private javax.swing.JLabel dataIconLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel doItLabel;
    private javax.swing.JPanel importanteJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel listJPanel;
    private javax.swing.JPanel listaJPanel;
    private javax.swing.JPanel navJPanel;
    private javax.swing.JLabel nomeListaLabel;
    private javax.swing.JPanel overviewJPanel;
    private javax.swing.JPanel quadro1JPanel;
    private javax.swing.JPanel quadro2JPanel;
    private javax.swing.JPanel quadro3JPanel;
    private javax.swing.JPanel tarefa1JPanel;
    private javax.swing.JPanel tarefa2JPanel;
    private javax.swing.JPanel tarefa3JPanel;
    private javax.swing.JPanel tarefa4JPanel;
    private javax.swing.JLabel tarefaLabel;
    private javax.swing.JLabel textoTarefaLabel;
    private javax.swing.JLabel trashIconLabel1;
    private javax.swing.JLabel trashIconLabel3;
    private javax.swing.JLabel trashIconLabel4;
    private javax.swing.JPanel usuarioJPanel;
    // End of variables declaration//GEN-END:variables
}
